openapi: 3.0.0
info:
  title: 'BileMo API'
  description: 'This is the documention for Bilemo API.'
  version: 1.0.0
paths:
  '/api/v1/customers/{customerId}':
    get:
      tags:
        - customer
      summary: 'Find customer by Id'
      description: 'Returns a single customer detail, you need to be an authenticated reseller'
      operationId: 'App\Controller\CustomerController::showCustomer'
      parameters:
        -
          name: customerId
          in: path
          description: 'Id of customer to return'
          required: true
          schema:
            type: integer
            format: int
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
              example:
                id: '200'
                firstname: Michel
                lastname: Cooper
                email: m.cooper@exemple.com
                reseller:
                  id: '24'
                  email: exemple@reseller.com
                  customer: '[]'
                  _links: ...
                _links:
                  self: ...
                  create: ...
                  delete: ...
        '404':
          description: 'Customer not found'
          content:
            application/json:
              schema: {  }
              example:
                message: 'This customer does not exist, or is not yours'
        '400':
          description: 'Invalid Id supplied'
          content:
            application/json:
              schema: {  }
              example:
                message: 'Bad request. Check your parameters, reminder that documention is here : ...'
        '401':
          description: 'Bearer token missing'
          content:
            application/json:
              schema: {  }
              example:
                code: '401'
                message: 'JWT Token not found'
    delete:
      tags:
        - customer
      summary: 'Deletes a customer'
      description: 'Delete a customer linked to your account, you need to be an authenticated reseller.'
      operationId: 'App\Controller\CustomerController::DeleteCustomer'
      parameters:
        -
          name: customerId
          in: path
          description: 'Customer Id to delete'
          required: true
          schema:
            type: integer
            format: int
      responses:
        '204':
          description: 'Customer deleted'
        '404':
          description: 'Customer not found'
          content:
            application/json:
              schema: {  }
              example:
                message: 'Customer does not exist'
        '403':
          description: 'Not authorized deletion'
          content:
            application/json:
              schema: {  }
              example:
                message: 'You are not authorized to delete this customer'
        '401':
          description: 'Bearer token missing'
          content:
            application/json:
              schema: {  }
              example:
                code: '401'
                message: 'JWT Token not found'
  /api/v1/customers:
    get:
      tags:
        - customer
      summary: 'Find all your customers'
      description: 'Returns a paginated list of all your customers, you need to be an authenticated reseller. The list of results is paginated, so if you need next page, add the page number as parameter in the query. Exemple : /api/v1/customers?page=2 '
      operationId: 'App\Controller\CustomerController::showCustomers'
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema: {  }
              example:
                current_page_number: '1'
                number_items_per_page: '10'
                total_items_count: '2'
                previous_page_link: 'null'
                next_page_link: 'null'
                items:
                  - { id: '200', firstname: Alice, lastname: Cooper, email: a.cooper@exemple.com, reseller: { id: '24', email: dev@phonecompany.com, customer: '[]', _links: '{...}' }, _links: { self: '{...}', create: '{...}', delete: '{...}' } }
                  - { id: '202', firstname: Emily, lastname: Alphin, email: alphin@exemple.com, reseller: { id: '24', email: dev@phonecompany.com, customer: '[]', _links: '{...}' }, _links: { self: '{...}', create: '{...}', delete: '{...}' } }
        '404':
          description: 'Customers not found'
          content:
            application/json:
              schema: {  }
              example:
                message: 'There is no customer for the moment'
        '400':
          description: 'Invalid request'
          content:
            application/json:
              schema: {  }
              example:
                message: 'Bad request. Check your parameters, reminder that documention is here : ...'
        '401':
          description: 'Bearer token missing'
          content:
            application/json:
              schema: {  }
              example:
                code: '401'
                message: 'JWT Token not found'
    post:
      tags:
        - customer
      summary: 'Creates a new customer'
      description: 'Creates a new customer linked to your account, you need to be an authenticated reseller'
      operationId: 'App\Controller\CustomerController::CreateCustomer'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                firstname:
                  description: 'Enter the firstname of the customer'
                  type: string
                lastname:
                  description: 'Enter the lastname of the customer'
                  type: string
                email:
                  description: 'Enter the email of the customer'
                  type: string
              type: object
              example:
                firstname: Emily
                lastname: Cooper
                email: emily.cooper@mymail.com
      responses:
        '201':
          description: 'Customer created'
          content:
            application/json:
              schema: {  }
              example:
                message: 'Customer created'
        '400':
          description: 'Invalid input, or duplicate customer'
          content:
            application/json:
              schema: {  }
              example:
                message: 'Bad request. Check your parameters, reminder that documention is here : ...'
        '401':
          description: 'Bearer token missing'
          content:
            application/json:
              schema: {  }
              example:
                code: '401'
                message: 'JWT Token not found'
  '/api/v1/phones/{phoneId}':
    get:
      tags:
        - phone
      summary: 'Find phone by Id'
      description: 'Returns a single phone detail, you need to be an authenticated reseller'
      operationId: 'App\Controller\PhoneController::showPhone'
      parameters:
        -
          name: phoneId
          in: path
          description: 'Id of phone to return'
          required: true
          schema:
            type: integer
            format: int
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Phone'
              example:
                id: '36'
                brand: Samsung
                description: 'Samsung Galaxy S10'
                price: '759.0'
                internal_reference: S10-G981BLBDEUB
                _links: ...
        '404':
          description: 'Phone not found, the id supplied does not exist'
          content:
            application/json:
              schema: {  }
              example:
                message: 'Phone not found'
        '400':
          description: 'Invalid Id supplied'
          content:
            application/json:
              schema: {  }
              example:
                message: 'Bad request. Check your parameters, reminder that documention is here : ...'
        '401':
          description: 'Bearer token missing'
          content:
            application/json:
              schema: {  }
              example:
                code: '401'
                message: 'JWT Token not found'
  /api/v1/phones:
    get:
      tags:
        - phone
      summary: 'Find all phones'
      description: 'Returns a paginated list of all phones, you need to be an authenticated reseller. The list of results is paginated, so if you need next page, add the page number as parameter in the query. Exemple : /api/v1/phones?page=2 '
      operationId: 'App\Controller\PhoneController::showPhones'
      responses:
        '200':
          description: 'successful operation'
          content:
            application/json:
              schema: {  }
              example:
                current_page_number: '1'
                number_items_per_page: '10'
                total_items_count: '2'
                previous_page_link: 'null'
                next_page_link: 'null'
                items:
                  - { id: '36', brand: Samsung, description: 'Samsung Galaxy S10', price: '759.0', internal_reference: S10-G981BLBDEUB, _links: ... }
                  - { id: '37', brand: Samsung, description: 'Samsung Galaxy S10+', price: '859.0', internal_reference: S10+-G981BLBDEUA, _links: ... }
        '404':
          description: 'There is no phone for the moment'
          content:
            application/json:
              schema: {  }
              example:
                message: 'There is no phone for the moment'
        '401':
          description: 'Bearer token missing'
          content:
            application/json:
              schema: {  }
              example:
                code: '401'
                message: 'JWT Token not found'
  '/api/v1/resellers/{resellerId}':
    get:
      tags:
        - reseller
      summary: 'Find reseller by Id'
      description: 'Returns a single reseller detail with all its customers, you need to be an authenticated admin'
      operationId: 'App\Controller\ResellerController::showReseller'
      parameters:
        -
          name: resellerId
          in: path
          description: 'ID of reseller to return'
          required: true
          schema:
            type: integer
            format: int
      responses:
        '200':
          description: 'successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reseller'
              example:
                id: '22'
                email: exemple@phonecompany.com
                customer:
                  - { id: '155', firstname: Natalia, lastname: Bashirian, email: coldy.san@yahoo.fr, _links: ... }
                  - { id: '156', firstname: Rachel, lastname: Dupont, email: rachel.d@free.fr, _links: ... }
                _links: ...
        '404':
          description: 'Reseller not found, the id supplied does not exist'
          content:
            application/json:
              schema: {  }
              example:
                message: 'Reseller not found'
        '400':
          description: 'Invalid Id supplied'
          content:
            application/json:
              schema: {  }
              example:
                message: 'Bad request. Check your parameters, reminder that documention is here : ...'
        '401':
          description: 'Bearer token missing'
          content:
            application/json:
              schema: {  }
              example:
                code: '401'
                message: 'JWT Token not found'
        '403':
          description: 'Not authorized access'
          content:
            application/json:
              schema: {  }
              example:
                message: 'You must be an admin to access this'
  /api/v1/resellers:
    get:
      tags:
        - reseller
      summary: 'Find all resellers'
      description: 'Returns a paginated list of all resellers, you need to be an authenticated admin. The list of results is paginated, so if you need next page, add the page number as parameter in the query. Exemple : /api/v1/resellers?page=2 '
      operationId: 'App\Controller\ResellerController::showResellers'
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema: {  }
              example:
                current_page_number: '1'
                number_items_per_page: '10'
                total_items_count: '2'
                previous_page_link: 'null'
                next_page_link: 'null'
                items:
                  - { id: '22', email: exemple@phonecompany.com, _links: ... }
                  - { id: '23', email: dev@phonereseller.com, _links: ... }
        '404':
          description: 'There is no reseller for the moment'
          content:
            application/json:
              schema: {  }
              example:
                message: 'There is no reseller for the moment'
        '401':
          description: 'Bearer token missing'
          content:
            application/json:
              schema: {  }
              example:
                code: '401'
                message: 'JWT Token not found'
        '403':
          description: 'Not authorized access'
          content:
            application/json:
              schema: {  }
              example:
                message: 'You must be an admin to access this'
  /api/v1/auth/signin:
    post:
      tags:
        - 'login and signin'
      summary: 'Signin to BileMo API'
      description: 'Signin to BileMo API, to create your reseller account'
      operationId: 'App\Controller\ResellerController::register'
      requestBody:
        description: 'Enter your email and the password of your choice. The password must respects following rules : minimum 8 characters, one uppercase, one lowercase, one number and one special character among #?!@$ %^&*-).'
        required: true
        content:
          application/json:
            schema:
              properties:
                email:
                  description: 'Enter your email as identifier, it must not be already taken'
                  type: string
                password:
                  description: 'Enter your chosen password, minimum 8 characters, one uppercase, one lowercase, one number and one special character among #?!@$ %^&*-).'
                  type: string
              type: object
              example:
                email: exemple@mymail.com
                password: mychosenpassword
      responses:
        '201':
          description: 'successful operation'
          content:
            application/json:
              schema: {  }
              example:
                message: 'You registered as a Reseller with success'
        '400':
          description: 'Invalid input'
          content:
            application/json:
              schema: {  }
              example:
                message: 'Bad request. Check your parameters, reminder that documention is here : ...'
  /api/v1/auth/login:
    post:
      tags:
        - 'login and signin'
      summary: 'Login to BileMo API to get your authentication token (Bearer token)'
      description: 'This can only be done by a registred reseller. It will let you obtain a token to make all others requests to the API that need authentication (almost all requests).'
      requestBody:
        description: 'Enter your credentials'
        required: true
        content:
          application/json:
            schema:
              properties:
                email:
                  description: 'Enter the email you registred with as identifier'
                  type: string
                password:
                  description: 'Enter your password'
                  type: string
              type: object
              example:
                email: exemple@mymail.com
                password: mypassword
      responses:
        '200':
          description: 'successful operation'
          content:
            application/json:
              schema:
                properties:
                  token: { description: 'Your precious token', type: string }
                type: object
                example:
                  token: eyJ7eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2MDIwNTU3NjAsImV4cCI6MTYwMjA1OTM2MCwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoiZGV2QGxkbGMuY29tIn0.SI5UDCNxGewjFJt86olg4DbmHx6Hl9E1UqGHAWhEXIiDJNWlKVq4_evwIuuk-EPoZV7BfEuAXU19_VFg1sGbEDhs20pzOC3G8pwKNZb_NTJ1E_tZ2Wq5GQpGw38uJa6qbYg4LoVs8EyMKrul-GQXA__Tm7blr9CU40PRrhMU4LdNf9wSitYFQ_9PJS0KpvjRfDgEMmt41QB-uUh2rUbNXcfUzfake5zeQQq_AoWMZBas3mUYdZe5np0jQvNHyuw2rit2OEIhVnZzHtMbVg6XACmYy9hHw--gQ7sjiSpqTq5ZeXW1b8AWTLQRiYMC3gLU89lvRHZs4GZLUZ4_c-4mxVNMBSf5J0yjHGW4buzVy5lx9rEY1tW9XeuYPKXKODisPNcX3p1j8XKwgEdjBC4LkhlDERFoADCYH75F5IURaMpj-HSs2U6fNcduQlm8NHd_y_ziywjj6a8qjvnIvUqWOMgYjSeesVBTZvWvNBiOqZ1yRdjGAmDw5KSPReTKPsq6IBHQersaZ_YMXwakVaTdJi7IZ-IhjJTIHuBxtlfYQLNyJWHQTTMfoJPto4FFwtNysKvus1v9RIKACoB9KZcYm2gN9dbKFZFenCWHm-pGeLWGzpKdI-2Km-egT7WX9X27BHHhhqx7RfKa7AWO9JR3G20vpbSBfx8YeVXWofesW2I
        '400':
          description: 'Invalid input'
          content:
            application/json:
              schema: {  }
              example:
                message: 'Bad request. Check your parameters, reminder that documention is here : ...'
        '401':
          description: 'Invalid credentials'
          content:
            application/json:
              schema: {  }
              example:
                code: '401'
                message: 'Invalid credentials.'
components:
  schemas:
    Customer:
      title: Customer
      description: 'Customer model'
      properties:
        id:
          title: Id
          description: Id
          format: int64
        firstname:
          title: Firstname
          description: 'customer Firstname'
        lastname:
          title: Lastname
          description: 'customer Lastname'
        email:
          title: Email
          description: 'customer Email'
        reseller:
          title: Reseller
          description: 'customer parent Reseller'
      type: object
    Phone:
      title: Phone
      description: 'Phone model'
      properties:
        id:
          title: Id
          description: Id
          format: int64
        brand:
          title: Brand
          description: 'phone Brand'
        model:
          title: Model
          description: 'phone Model'
        description:
          title: Description
          description: 'phone Description'
        price:
          title: Price
          description: 'phone Price'
          format: float
        internalReference:
          title: 'Internal Reference'
          description: 'phone Internal Reference'
      type: object
    Reseller:
      title: Reseller
      description: 'Reseller model'
      properties:
        id:
          title: Id
          description: Id
          format: int64
        email:
          title: Email
          description: 'reseller Email'
        customer:
          title: Customer
          description: 'Customer of the Reseller'
      type: object
